#!/bin/bash
echo "=== 设备基本信息 ==="
echo "设备序列号: $(adb shell getprop ro.serialno)"
echo "设备型号: $(adb shell getprop ro.product.model)"
echo "制造商: $(adb shell getprop ro.product.manufacturer)"
echo "Android 版本: $(adb shell getprop ro.build.version.release)"
echo "API 级别: $(adb shell getprop ro.build.version.sdk)"
echo "Build ID: $(adb shell getprop ro.build.id)"
echo ""
echo "=== 系统信息 ==="
echo "屏幕分辨率: $(adb shell wm size | grep -o '[0-9]*x[0-9]*')"
echo "屏幕密度: $(adb shell wm density | grep -o '[0-9]*')"
echo ""
echo "=== 已安装的目标应用 ==="
echo "闲鱼: $(adb shell pm list packages | grep -i xianyu || echo '未安装')"
echo "小红书: $(adb shell pm list packages | grep -i red || echo '未安装')"
echo "抖音: $(adb shell pm list packages | grep -i douyin || echo '未安装')"
echo "微信: $(adb shell pm list packages | grep -i wechat || echo '未安装')"
echo ""
echo "=== Companion APK 状态 ==="
adb shell pm list packages | grep cloudctl || echo "Companion APK 未安装"
