package com.company.cloudctl.companion.control

import com.company.cloudctl.companion.data.PendingControlAck

/**
 * B17 control-plane sync engine (contract control-plane/v1@20260917.1 §2).
 *
 * Catch-up is cursor-first (§2.1), snapshot is the convergence fallback
 * (§2.2) — any 410 CURSOR_TOO_OLD immediately reconciles from the snapshot.
 * The heartbeat escape channel (§2.3) feeds [onHeartbeatResponse]: a lagging
 * watermark triggers the cursor pull on the next [syncOnce], and inline
 * events are applied through the same idempotent transactional path.
 *
 * All state lives in [ControlStateStore]; this class holds only the volatile
 * last-seen server watermark, so it is safe to share across the presence and
 * sync loops.
 */
class ControlSyncClient(
    private val transport: ControlPlaneTransport,
    private val state: ControlStateStore,
) {
    @Volatile
    var knownServerWatermark: Long = 0L
        private set

    /** §4 ack upload + §2.1 cursor catch-up; never gated by any local execution state. */
    fun syncOnce(forceSnapshot: Boolean = false): ControlSyncOutcome {
        // Catch up first so acks generated by THIS round's events upload in
        // the same pass (minimal cancel→ack latency).
        val outcome = if (forceSnapshot) {
            applySnapshot()
            ControlSyncOutcome(reconciledFromSnapshot = true, cursorAdvanced = true)
        } else {
            cursorCatchUp()
        }
        deliverPendingAcks()
        return outcome
    }

    /** §2.3: ingest watermark + ≤2 inline events from the device heartbeat response. */
    fun onHeartbeatResponse(controlHighWatermark: Long, inlineEvents: List<ControlEvent>) {
        if (controlHighWatermark > knownServerWatermark) knownServerWatermark = controlHighWatermark
        if (inlineEvents.isNotEmpty()) {
            val target = inlineEvents.maxOf { it.seq }
            state.applyInlineEvents(inlineEvents, target)
        }
    }

    /** §2.3 request augmentation: lastAppliedControlSeq + safetyBarrier. */
    fun heartbeatRequestFields(lastApplied: Long, safetyBarrier: String): org.json.JSONObject =
        org.json.JSONObject()
            .put("lastAppliedControlSeq", lastApplied)
            .put("safetyBarrier", safetyBarrier)

    private fun cursorCatchUp(): ControlSyncOutcome {
        var after = state.lastAppliedControlSeq()
        var advanced = false
        repeat(MAX_BATCHES_PER_SYNC) {
            val batch = try {
                transport.fetchControlEvents(after, BATCH_LIMIT)
            } catch (tooOld: ControlCursorTooOldException) {
                applySnapshot()
                return ControlSyncOutcome(reconciledFromSnapshot = true, cursorAdvanced = true)
            }
            state.applyControlBatch(batch, target = batch.through)
            if (batch.highWatermark > knownServerWatermark) knownServerWatermark = batch.highWatermark
            advanced = advanced || batch.through > after
            if (batch.events.isEmpty() || batch.through >= batch.highWatermark) {
                return ControlSyncOutcome(reconciledFromSnapshot = false, cursorAdvanced = advanced)
            }
            after = batch.through
        }
        return ControlSyncOutcome(reconciledFromSnapshot = false, cursorAdvanced = advanced)
    }

    /** §2.2 authoritative snapshot: mirror converges, cursor jumps to the watermark. */
    private fun applySnapshot() {
        val snapshot = transport.fetchReconcileSnapshot()
        state.applyReconcileSnapshot(snapshot)
        if (snapshot.controlHighWatermark > knownServerWatermark) {
            knownServerWatermark = snapshot.controlHighWatermark
        }
    }

    /**
     * §4: acks upload after the mirror settled. A pending APPLIED whose task
     * settled into RECONCILING is rewritten to DEFERRED at send time.
     * Non-retryable rejections drop the ack (the server already owns the
     * truth); retryable errors abort the pass and retry next round.
     */
    private fun deliverPendingAcks() {
        for (ack in state.pendingControlAcks()) {
            if (state.isTaskLocallyRunning(ack.taskId)) continue
            val (result, reason) = resolveAck(ack)
            try {
                transport.postControlAck(ack.taskId, ack.taskRevision, result, reason)
                state.removeControlAck(ack.id)
            } catch (rejected: ControlPlaneHttpException) {
                if (!rejected.retryable) state.removeControlAck(ack.id) else return
            }
        }
    }

    private fun resolveAck(ack: PendingControlAck): Pair<String, String?> =
        if (ack.result == ControlAckResults.CANCEL_APPLIED && state.isTaskReconciling(ack.taskId)) {
            ControlAckResults.CANCEL_DEFERRED_RECONCILING to
                (ack.reason ?: "settled into RECONCILING; manual reconciliation required")
        } else {
            ack.result to ack.reason
        }

    data class ControlSyncOutcome(val reconciledFromSnapshot: Boolean, val cursorAdvanced: Boolean)

    private companion object {
        const val BATCH_LIMIT = 50
        const val MAX_BATCHES_PER_SYNC = 10
    }
}
