ALTER TABLE mobile_task ADD COLUMN IF NOT EXISTS resume_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE mobile_task ADD COLUMN IF NOT EXISTS pause_ack_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE mobile_task ADD COLUMN IF NOT EXISTS reconciliation JSON NOT NULL DEFAULT '{}';
