"""initial control plane schema

Revision ID: 20260831_0001
Revises:
Create Date: 2026-08-31 09:37:48.393926
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260831_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apk_artifact",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("package_name", sa.String(length=255), nullable=False),
        sa.Column("version_name", sa.String(length=120), nullable=False),
        sa.Column("version_code", sa.Integer(), nullable=False),
        sa.Column("signature_digest", sa.String(length=128), nullable=False),
        sa.Column("min_sdk", sa.Integer(), nullable=False),
        sa.Column("target_sdk", sa.Integer(), nullable=False),
        sa.Column("abis", sa.JSON(), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column("sbom_ref", sa.String(length=512), nullable=False),
        sa.Column("scan_status", sa.String(length=32), nullable=False),
        sa.Column("source_ref", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "sha256"),
    )
    op.create_index(op.f("ix_apk_artifact_tenant_id"), "apk_artifact", ["tenant_id"], unique=False)
    op.create_table(
        "audit_event",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=160), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=False),
        sa.Column("request_id", sa.String(length=255), nullable=False),
        sa.Column("workflow_id", sa.String(length=255), nullable=True),
        sa.Column("device_id", sa.String(length=36), nullable=True),
        sa.Column("edge_id", sa.String(length=36), nullable=True),
        sa.Column("before_hash", sa.String(length=64), nullable=True),
        sa.Column("after_hash", sa.String(length=64), nullable=True),
        sa.Column("result", sa.String(length=32), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_event_tenant_id"), "audit_event", ["tenant_id"], unique=False)
    op.create_table(
        "automation_package_version",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("artifact_sha256", sa.String(length=64), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("signature_key_id", sa.String(length=160), nullable=False),
        sa.Column("sbom_ref", sa.String(length=512), nullable=False),
        sa.Column("production_qualified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", "version"),
    )
    op.create_index(
        op.f("ix_automation_package_version_tenant_id"),
        "automation_package_version",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "content_item",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_content_item_tenant_id"), "content_item", ["tenant_id"], unique=False)
    op.create_table(
        "device_lease",
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("lease_id", sa.String(length=36), nullable=False),
        sa.Column("owner_workflow_id", sa.String(length=255), nullable=False),
        sa.Column("fencing_token", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("device_id"),
        sa.UniqueConstraint("lease_id"),
    )
    op.create_index(op.f("ix_device_lease_tenant_id"), "device_lease", ["tenant_id"], unique=False)
    op.create_table(
        "edge_node",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("logical_name", sa.String(length=160), nullable=False),
        sa.Column("certificate_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "logical_name"),
    )
    op.create_index(op.f("ix_edge_node_tenant_id"), "edge_node", ["tenant_id"], unique=False)
    op.create_table(
        "media_asset",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=160), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("source_asset_id", sa.String(length=36), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "sha256"),
    )
    op.create_index(op.f("ix_media_asset_tenant_id"), "media_asset", ["tenant_id"], unique=False)
    op.create_table(
        "operation_task",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("operation_key", sa.String(length=160), nullable=False),
        sa.Column("module", sa.String(length=80), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_sha256", sa.String(length=64), nullable=False),
        sa.Column("requested_by", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("succeeded_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("blocked_count", sa.Integer(), nullable=False),
        sa.Column("canceled_count", sa.Integer(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("result_summary", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key"),
    )
    op.create_index(op.f("ix_operation_task_module"), "operation_task", ["module"], unique=False)
    op.create_index(
        op.f("ix_operation_task_operation_key"), "operation_task", ["operation_key"], unique=False
    )
    op.create_index(op.f("ix_operation_task_status"), "operation_task", ["status"], unique=False)
    op.create_index(
        op.f("ix_operation_task_tenant_id"), "operation_task", ["tenant_id"], unique=False
    )
    op.create_table(
        "outbox_event",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=160), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claim_owner", sa.String(length=255), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outbox_event_event_type"), "outbox_event", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_outbox_event_tenant_id"), "outbox_event", ["tenant_id"], unique=False)
    op.create_table(
        "tenant",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "content_revision",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("content_id", sa.String(length=36), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_id", "revision_no"),
    )
    op.create_index(
        op.f("ix_content_revision_tenant_id"), "content_revision", ["tenant_id"], unique=False
    )
    op.create_table(
        "device",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("edge_id", sa.String(length=36), nullable=False),
        sa.Column("logical_name", sa.String(length=160), nullable=False),
        sa.Column("android_version", sa.String(length=32), nullable=True),
        sa.Column("lamda_version", sa.String(length=32), nullable=True),
        sa.Column("target_app_versions", sa.JSON(), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("maintenance", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("fencing_counter", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["edge_id"],
            ["edge_node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "logical_name"),
    )
    op.create_index(op.f("ix_device_tenant_id"), "device", ["tenant_id"], unique=False)
    op.create_table(
        "operation_item",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("evidence_refs", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["operation_task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "resource_id"),
    )
    op.create_index(op.f("ix_operation_item_task_id"), "operation_item", ["task_id"], unique=False)
    op.create_index(
        op.f("ix_operation_item_tenant_id"), "operation_item", ["tenant_id"], unique=False
    )
    op.create_table(
        "user_account",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("oidc_subject", sa.String(length=255), nullable=False),
        sa.Column("roles", sa.JSON(), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "oidc_subject"),
    )
    op.create_index(op.f("ix_user_account_tenant_id"), "user_account", ["tenant_id"], unique=False)
    op.create_table(
        "publish_plan",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_sha256", sa.String(length=64), nullable=False),
        sa.Column("creator_id", sa.String(length=36), nullable=False),
        sa.Column("content_revision_id", sa.String(length=36), nullable=False),
        sa.Column("automation_package_version_id", sa.String(length=36), nullable=False),
        sa.Column("platform", sa.String(length=160), nullable=False),
        sa.Column("schedule", sa.JSON(), nullable=False),
        sa.Column("execution", sa.JSON(), nullable=False),
        sa.Column("approval_policy", sa.String(length=64), nullable=False),
        sa.Column("targets", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("workflow_id", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["automation_package_version_id"],
            ["automation_package_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["content_revision_id"],
            ["content_revision.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key"),
    )
    op.create_index(op.f("ix_publish_plan_tenant_id"), "publish_plan", ["tenant_id"], unique=False)
    op.create_table(
        "approval",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("creator_id", sa.String(length=36), nullable=False),
        sa.Column("approver_id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["publish_plan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_approval_tenant_id"), "approval", ["tenant_id"], unique=False)
    op.create_table(
        "publish_snapshot",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("content_revision_id", sa.String(length=36), nullable=False),
        sa.Column("automation_package_version_id", sa.String(length=36), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["publish_plan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id"),
    )
    op.create_index(
        op.f("ix_publish_snapshot_tenant_id"), "publish_snapshot", ["tenant_id"], unique=False
    )
    op.create_table(
        "publish_target",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("result_detail", sa.Text(), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["publish_plan.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["publish_snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_publish_target_tenant_id"), "publish_target", ["tenant_id"], unique=False
    )
    op.create_table(
        "commit_intent",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("fencing_token", sa.Integer(), nullable=False),
        sa.Column("before_commit_evidence_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["publish_target.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_id", "attempt_no"),
    )
    op.create_index(
        op.f("ix_commit_intent_tenant_id"), "commit_intent", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_commit_intent_tenant_id"), table_name="commit_intent")
    op.drop_table("commit_intent")
    op.drop_index(op.f("ix_publish_target_tenant_id"), table_name="publish_target")
    op.drop_table("publish_target")
    op.drop_index(op.f("ix_publish_snapshot_tenant_id"), table_name="publish_snapshot")
    op.drop_table("publish_snapshot")
    op.drop_index(op.f("ix_approval_tenant_id"), table_name="approval")
    op.drop_table("approval")
    op.drop_index(op.f("ix_publish_plan_tenant_id"), table_name="publish_plan")
    op.drop_table("publish_plan")
    op.drop_index(op.f("ix_user_account_tenant_id"), table_name="user_account")
    op.drop_table("user_account")
    op.drop_index(op.f("ix_operation_item_tenant_id"), table_name="operation_item")
    op.drop_index(op.f("ix_operation_item_task_id"), table_name="operation_item")
    op.drop_table("operation_item")
    op.drop_index(op.f("ix_device_tenant_id"), table_name="device")
    op.drop_table("device")
    op.drop_index(op.f("ix_content_revision_tenant_id"), table_name="content_revision")
    op.drop_table("content_revision")
    op.drop_table("tenant")
    op.drop_index(op.f("ix_outbox_event_tenant_id"), table_name="outbox_event")
    op.drop_index(op.f("ix_outbox_event_event_type"), table_name="outbox_event")
    op.drop_table("outbox_event")
    op.drop_index(op.f("ix_operation_task_tenant_id"), table_name="operation_task")
    op.drop_index(op.f("ix_operation_task_status"), table_name="operation_task")
    op.drop_index(op.f("ix_operation_task_operation_key"), table_name="operation_task")
    op.drop_index(op.f("ix_operation_task_module"), table_name="operation_task")
    op.drop_table("operation_task")
    op.drop_index(op.f("ix_media_asset_tenant_id"), table_name="media_asset")
    op.drop_table("media_asset")
    op.drop_index(op.f("ix_edge_node_tenant_id"), table_name="edge_node")
    op.drop_table("edge_node")
    op.drop_index(op.f("ix_device_lease_tenant_id"), table_name="device_lease")
    op.drop_table("device_lease")
    op.drop_index(op.f("ix_content_item_tenant_id"), table_name="content_item")
    op.drop_table("content_item")
    op.drop_index(
        op.f("ix_automation_package_version_tenant_id"), table_name="automation_package_version"
    )
    op.drop_table("automation_package_version")
    op.drop_index(op.f("ix_audit_event_tenant_id"), table_name="audit_event")
    op.drop_table("audit_event")
    op.drop_index(op.f("ix_apk_artifact_tenant_id"), table_name="apk_artifact")
    op.drop_table("apk_artifact")
    # ### end Alembic commands ###
